export type Theme = Record<string, Record<string, string>>

export const themes: Record<string, Theme> = {
  vscDarkPlus: {
    base: {
      color: '#d4d4d4',
      fontSize: '13px',
      textShadow: 'none',
      fontFamily: "Menlo, Monaco, Consolas, 'Andale Mono', 'Ubuntu Mono', 'Courier New', monospace",
      direction: 'ltr',
      textAlign: 'left',
      whiteSpace: 'pre',
      wordSpacing: 'normal',
      wordBreak: 'normal',
      lineHeight: '1.5',
      MozTabSize: '4',
      OTabSize: '4',
      tabSize: '4',
      WebkitHyphens: 'none',
      MozHyphens: 'none',
      hyphens: 'none',
      padding: '1em',
      margin: '.5em 0',
      overflow: 'auto',
      backgroundColor: '#1e1e1e',
    },
    comment: { color: '#6a9955' },
    prolog: { color: '#6a9955' },
    punctuation: { color: '#d4d4d4' },
    property: { color: '#9cdcfe' },
    tag: { color: '#569cd6' },
    boolean: { color: '#569cd6' },
    number: { color: '#b5cea8' },
    constant: { color: '#9cdcfe' },
    symbol: { color: '#b5cea8' },
    inserted: { color: '#b5cea8' },
    unit: { color: '#b5cea8' },
    selector: { color: '#d7ba7d' },
    'attr-name': { color: '#9cdcfe' },
    string: { color: '#ce9178' },
    char: { color: '#ce9178' },
    builtin: { color: '#ce9178' },
    deleted: { color: '#ce9178' },
    operator: { color: '#d4d4d4' },
    entity: { color: '#569cd6' },
    atrule: { color: '#ce9178' },
    keyword: { color: '#569CD6' },
    function: { color: '#dcdcaa' },
    regex: { color: '#d16969' },
    important: { color: '#569cd6' },
    italic: { fontStyle: 'italic' },
    'class-name': { color: '#4ec9b0' },
    'maybe-class-name': { color: '#4ec9b0' },
    console: { color: '#9cdcfe' },
    parameter: { color: '#9cdcfe' },
    interpolation: { color: '#9cdcfe' },
    variable: { color: '#9cdcfe' },
    escape: { color: '#d7ba7d' },
    cdata: { color: '#808080' },
    'attr-value': { color: '#ce9178' },
    namespace: { color: '#4ec9b0' },
  },
  vs: {
    base: {
      color: '#393A34',
      fontFamily: "'Consolas', 'Bitstream Vera Sans Mono', 'Courier New', Courier, monospace",
      direction: 'ltr',
      textAlign: 'left',
      whiteSpace: 'pre',
      wordSpacing: 'normal',
      wordBreak: 'normal',
      fontSize: '.9em',
      lineHeight: '1.2em',
      MozTabSize: '4',
      OTabSize: '4',
      tabSize: '4',
      WebkitHyphens: 'none',
      MozHyphens: 'none',
      hyphens: 'none',
      padding: '1em',
      margin: '.5em 0',
      overflow: 'auto',
      border: '1px solid #dddddd',
      backgroundColor: 'white',
    },
    comment: { color: '#008000', fontStyle: 'italic' },
    prolog: { color: '#008000', fontStyle: 'italic' },
    doctype: { color: '#008000', fontStyle: 'italic' },
    cdata: { color: '#008000', fontStyle: 'italic' },
    namespace: { opacity: '.7' },
    string: { color: '#A31515' },
    punctuation: { color: '#393A34' },
    operator: { color: '#393A34' },
    url: { color: '#36acaa' },
    symbol: { color: '#36acaa' },
    number: { color: '#36acaa' },
    boolean: { color: '#36acaa' },
    variable: { color: '#36acaa' },
    constant: { color: '#36acaa' },
    inserted: { color: '#36acaa' },
    atrule: { color: '#0000ff' },
    keyword: { color: '#0000ff' },
    'attr-value': { color: '#0000ff' },
    function: { color: '#393A34' },
    deleted: { color: '#9a050f' },
    selector: { color: '#800000' },
    important: { color: '#e90', fontWeight: 'bold' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
    'class-name': { color: '#2B91AF' },
    tag: { color: '#800000' },
    'attr-name': { color: '#ff0000' },
    property: { color: '#ff0000' },
    regex: { color: '#ff0000' },
    entity: { color: '#ff0000' },
  },
  oneDark: {
    base: {
      backgroundColor: '#282c34',
      color: '#abb2bf',
      textShadow: '0 1px rgba(0, 0, 0, 0.3)',
      fontFamily: "'Fira Code', 'Fira Mono', Menlo, Consolas, 'DejaVu Sans Mono', monospace",
      direction: 'ltr',
      textAlign: 'left',
      whiteSpace: 'pre',
      wordSpacing: 'normal',
      wordBreak: 'normal',
      lineHeight: '1.5',
      MozTabSize: '2',
      OTabSize: '2',
      tabSize: '2',
      WebkitHyphens: 'none',
      MozHyphens: 'none',
      hyphens: 'none',
      padding: '1em',
      margin: '0.5em 0',
      overflow: 'auto',
      borderRadius: '0.3em',
    },
    comment: { color: '#5c6370', fontStyle: 'italic' },
    prolog: { color: '#5c6370' },
    cdata: { color: '#5c6370' },
    doctype: { color: '#abb2bf' },
    punctuation: { color: '#abb2bf' },
    entity: { color: '#abb2bf', cursor: 'help' },
    'attr-name': { color: '#d19a66' },
    'class-name': { color: '#d19a66' },
    boolean: { color: '#d19a66' },
    constant: { color: '#d19a66' },
    number: { color: '#d19a66' },
    atrule: { color: '#d19a66' },
    keyword: { color: '#c678dd' },
    property: { color: '#e06c75' },
    tag: { color: '#e06c75' },
    symbol: { color: '#e06c75' },
    deleted: { color: '#e06c75' },
    important: { color: '#e06c75' },
    selector: { color: '#98c379' },
    string: { color: '#98c379' },
    char: { color: '#98c379' },
    builtin: { color: '#98c379' },
    inserted: { color: '#98c379' },
    regex: { color: '#98c379' },
    'attr-value': { color: '#98c379' },
    variable: { color: '#61afef' },
    operator: { color: '#61afef' },
    function: { color: '#61afef' },
    url: { color: '#56b6c2' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
    namespace: { opacity: '0.8' },
  },
  oneLight: {
    base: {
      backgroundColor: '#fafafa',
      color: '#383a42',
      fontFamily: "'Fira Code', 'Fira Mono', Menlo, Consolas, 'DejaVu Sans Mono', monospace",
      direction: 'ltr',
      textAlign: 'left',
      whiteSpace: 'pre',
      wordSpacing: 'normal',
      wordBreak: 'normal',
      lineHeight: '1.5',
      MozTabSize: '2',
      OTabSize: '2',
      tabSize: '2',
      WebkitHyphens: 'none',
      MozHyphens: 'none',
      hyphens: 'none',
      padding: '1em',
      margin: '0.5em 0',
      overflow: 'auto',
      borderRadius: '0.3em',
    },
    comment: { color: '#a0a1a7', fontStyle: 'italic' },
    prolog: { color: '#a0a1a7' },
    cdata: { color: '#a0a1a7' },
    doctype: { color: '#383a42' },
    punctuation: { color: '#383a42' },
    entity: { color: '#383a42', cursor: 'help' },
    'attr-name': { color: '#b76b01' },
    'class-name': { color: '#b76b01' },
    boolean: { color: '#b76b01' },
    constant: { color: '#b76b01' },
    number: { color: '#b76b01' },
    atrule: { color: '#b76b01' },
    keyword: { color: '#a626a4' },
    property: { color: '#e45649' },
    tag: { color: '#e45649' },
    symbol: { color: '#e45649' },
    deleted: { color: '#e45649' },
    important: { color: '#e45649' },
    selector: { color: '#50a14f' },
    string: { color: '#50a14f' },
    char: { color: '#50a14f' },
    builtin: { color: '#50a14f' },
    inserted: { color: '#50a14f' },
    regex: { color: '#50a14f' },
    'attr-value': { color: '#50a14f' },
    variable: { color: '#4078f2' },
    operator: { color: '#4078f2' },
    function: { color: '#4078f2' },
    url: { color: '#0184bc' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' },
    namespace: { opacity: '0.8' },
  },
}
